# Generated by Django 4.2.5 on 2023-11-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_folder_file_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_folder',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='image',
            field=models.ImageField(default='file_images/folder.png', upload_to='file_images/'),
        ),
    ]
