# Generated by Django 4.2.5 on 2023-11-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_folder_parent_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
