# Generated by Django 4.2.5 on 2023-11-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0006_alter_folder_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
    ]
